// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiy4YVZvQKmOltLq0Ymdw6sl-Nx6cJXoQ',
    appId: '1:1097226990560:web:f3eee42a7def85acc0f185',
    messagingSenderId: '1097226990560',
    projectId: 'rizzmusic-ff756',
    authDomain: 'rizzmusic-ff756.firebaseapp.com',
    databaseURL: 'https://rizzmusic-ff756-default-rtdb.firebaseio.com',
    storageBucket: 'rizzmusic-ff756.firebasestorage.app',
    measurementId: 'G-NRKRWEGBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqdm4oHeFY9aE46AN4PYkoeFC22bldIU',
    appId: '1:1097226990560:android:22e320b0136d576ac0f185',
    messagingSenderId: '1097226990560',
    projectId: 'rizzmusic-ff756',
    databaseURL: 'https://rizzmusic-ff756-default-rtdb.firebaseio.com',
    storageBucket: 'rizzmusic-ff756.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPZIMrlyXeI4BOVClUOvAZzfixsYa1Qg',
    appId: '1:1097226990560:ios:a3eae16279bd35d5c0f185',
    messagingSenderId: '1097226990560',
    projectId: 'rizzmusic-ff756',
    databaseURL: 'https://rizzmusic-ff756-default-rtdb.firebaseio.com',
    storageBucket: 'rizzmusic-ff756.firebasestorage.app',
    iosClientId: '1097226990560-gn232sovgrhdfpg1fhsn32ur4a9mqf12.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizzmusicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtPZIMrlyXeI4BOVClUOvAZzfixsYa1Qg',
    appId: '1:1097226990560:ios:a3eae16279bd35d5c0f185',
    messagingSenderId: '1097226990560',
    projectId: 'rizzmusic-ff756',
    databaseURL: 'https://rizzmusic-ff756-default-rtdb.firebaseio.com',
    storageBucket: 'rizzmusic-ff756.firebasestorage.app',
    iosClientId: '1097226990560-gn232sovgrhdfpg1fhsn32ur4a9mqf12.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizzmusicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiy4YVZvQKmOltLq0Ymdw6sl-Nx6cJXoQ',
    appId: '1:1097226990560:web:7988a82196385fbcc0f185',
    messagingSenderId: '1097226990560',
    projectId: 'rizzmusic-ff756',
    authDomain: 'rizzmusic-ff756.firebaseapp.com',
    databaseURL: 'https://rizzmusic-ff756-default-rtdb.firebaseio.com',
    storageBucket: 'rizzmusic-ff756.firebasestorage.app',
    measurementId: 'G-M7Z3KYPP6Q',
  );


}
